INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供冷季', '住宅', 'Ⅰ', '25.5-27.0	', '40-60	', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供冷季', '住宅', 'Ⅱ', '26.5-29	', '≤70	', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供冷季', '办公', 'Ⅰ', '25.5-27.0	', '40-60	', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供冷季', '办公', 'Ⅱ', '25.5-28.5	', '≤70	', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供暖季', '住宅', 'Ⅰ', '18.5-21.0', '≥30', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供暖季', '住宅', 'Ⅱ', '17.5-21.0', '—', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供暖季', '办公', 'Ⅰ', '19.0-21.0', '≥30', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('严寒地区', '供暖季', '办公', 'Ⅱ', '18.0-21.0', '—', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供冷季', '住宅', 'Ⅰ', '25.5-28.5', '40-60', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供冷季', '住宅', 'Ⅱ', '25.5-29.5', '≤70', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供冷季', '办公', 'Ⅰ', '25.5-28.0', '40-60', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供冷季', '办公', 'Ⅱ', '25.5-29.0', '≤70', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供暖季', '住宅', 'Ⅰ', '16.5-20.0', '≥30', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供暖季', '住宅', 'Ⅱ', '16.5-20.0', '—', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供暖季', '办公', 'Ⅰ', '17.5-20.0', '≥30', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬冷地区', '供暖季', '办公', 'Ⅱ', '16.5-20.0', '—', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供冷季', '住宅', 'Ⅰ', '26.0-29.0', '40-60', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供冷季', '住宅', 'Ⅱ', '26.0-30.0', '≤70', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供冷季', '办公', 'Ⅰ', '26.0-28.0', '40-60', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供冷季', '办公', 'Ⅱ', '26.0-29.0', '≤70', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供暖季', '住宅', 'Ⅰ', '20-22	', '≥30	', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供暖季', '住宅', 'Ⅱ', '18-22	', '—', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供暖季', '办公', 'Ⅰ', '20-22	', '≥30', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('夏热冬暖地区', '供暖季', '办公', 'Ⅱ', '18-22	', '—', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供冷季', '住宅', 'Ⅰ', '25.0-28.5', '40-60', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供冷季', '住宅', 'Ⅱ', '25.0-29.5', '≤70', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供冷季', '办公', 'Ⅰ', '25.5-28.0', '40-60', '≤0.25');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供冷季', '办公', 'Ⅱ', '25.5-29.0', '≤70', '≤0.3');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供暖季', '住宅', 'Ⅰ', '16.5-20.0', '≥30', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供暖季', '住宅', 'Ⅱ', '16.0-20.0', '—', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供暖季', '办公', 'Ⅰ', '17.5-20.0', '≥30', '≤0.2');
INSERT INTO `iddp` (`climates`, `season`, `arch_type`, `arch_level`, `temp_range`, `humi_range`, `wind_speed`) VALUES ('寒冷地区', '供暖季', '办公', 'Ⅱ', '16.5-20.0', '—', '≤0.2');
